create table if not exists public.analytics_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  page_title text,
  country text,
  region text,
  city text,
  latitude double precision,
  longitude double precision,
  timezone text,
  language text,
  user_agent text,
  device_type text,
  referrer text
);

create index if not exists analytics_visits_created_at_idx on public.analytics_visits (created_at desc);
create index if not exists analytics_visits_country_idx on public.analytics_visits (country);
create index if not exists analytics_visits_path_idx on public.analytics_visits (path);

create table if not exists public.booking_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  email text not null,
  phone text not null,
  hunt text not null,
  country text,
  region text,
  city text,
  latitude double precision,
  longitude double precision,
  source_path text,
  status text not null default 'lead_captured',
  payment_provider text,
  payment_ref text
);

alter table public.booking_leads
  add column if not exists country text,
  add column if not exists region text,
  add column if not exists city text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

create index if not exists booking_leads_created_at_idx on public.booking_leads (created_at desc);
create index if not exists booking_leads_status_idx on public.booking_leads (status);
create index if not exists booking_leads_hunt_idx on public.booking_leads (hunt);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  role text not null default 'admin'
);

alter table public.analytics_visits enable row level security;
alter table public.booking_leads enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists analytics_insert_public on public.analytics_visits;
create policy analytics_insert_public
on public.analytics_visits
for insert
to anon, authenticated
with check (true);

drop policy if exists booking_insert_public on public.booking_leads;
create policy booking_insert_public
on public.booking_leads
for insert
to anon, authenticated
with check (true);

drop policy if exists analytics_select_admin on public.analytics_visits;
create policy analytics_select_admin
on public.analytics_visits
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
  )
);

drop policy if exists booking_select_admin on public.booking_leads;
create policy booking_select_admin
on public.booking_leads
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
  )
);

drop policy if exists admin_users_select_self on public.admin_users;
create policy admin_users_select_self
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());
